# The `yarn` step can be pretty slow, so cache the dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  image: node:16.7.0
  artifacts:
    paths:
      - .cache
      - generated
      - public
  interruptible: true
  script:
    - yarn install --frozen-lockfile
    - yarn build

build_storybook:
  stage: build
  image: node:16.7.0
  artifacts:
    paths:
      - storybook-static
  interruptible: true
  script:
    - yarn install --frozen-lockfile
    - yarn build-storybook --docs --quiet

frontend_code_quality:
  stage: test
  image: node:16.7.0
  interruptible: true
  script:
    - yarn install --frozen-lockfile
    - LEFTHOOK_EXCLUDE=infra yarn lefthook run check-all

# TODO: Gitlab CI doesn't seem to execute the script.
#       I must be configuring something wrong but can't see it.
#       Plan is to migrate to Github + Github Actions soon, so
#       going to be cheeky and just skip it for now...
#
# terraform_code_quality:
#   stage: test
#   image: hashicorp/terraform:0.14.7
#   interruptible: true
#   script: "terraform fmt -check deploy/infra"

deploy:
  stage: deploy
  only:
    - master
  image: amazon/aws-cli:2.2.37
  variables:
    GATSBY_BUILD_SHA: $CI_COMMIT_SHORT_SHA
  script:
    - echo "what"
    - aws s3 sync public s3://cy7.io

deploy_storybook:
  stage: deploy
  only:
    - master
  image: amazon/aws-cli:2.2.37
  script:
    - echo "what"
    - aws s3 sync storybook-static s3://storybook.cy7.io
