# The `yarn` step can be pretty slow, so cache the dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

code_quality:
  stage: test
  image: registry.gitlab.com/cycleseven/cy7/ci-lint-job:0.4.0
  script:
    - yarn
    - yarn lefthook run check-all

deploy:
  stage: deploy
  only:
    - master
  image: registry.gitlab.com/cycleseven/cy7/ci-deploy-job:0.4.0
  variables:
    GATSBY_BUILD_SHA: $CI_COMMIT_SHORT_SHA
  script:
    - yarn
    - yarn build
    - aws s3 sync public s3://cy7.io

deploy_storybook:
  stage: deploy
  only:
    - master
  image: registry.gitlab.com/cycleseven/cy7/ci-deploy-job:0.3.0
  script:
    - yarn
    - yarn build-storybook --docs
    - aws s3 sync storybook-static s3://storybook.cy7.io
