service: cy7-redirect-lambda

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 5
  memorySize: 128
  tags:
    project: website
  stackTags:
    project: website

package:
  exclude:
    - node_modules/**
    - pnpm-lock.yaml

functions:
  redirect:
    handler: handlers.redirect
  subdirectoryIndex:
    handler: handlers.subdirectoryIndex

resources:
  Resources:
    IamRoleLambdaExecution:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
  Outputs:
    SubdirectoryIndexLambdaFunctionQualifiedArn:
      Export:
        Name: "cy7-subdirectory-index-lambda-arn"
    RedirectLambdaFunctionQualifiedArn:
      Export:
        Name: "cy7-redirect-lambda-arn"
