name: Check frontend code quality
on:
  workflow_call:
jobs:
  check-frontend-code-quality:
    name: Check frontend code quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.18.0
      - name: Download generated GraphQL types
        uses: actions/download-artifact@v2
        with:
          name: generated
          path: generated
      - uses: ./.github/actions/yarn-install
      - run: LEFTHOOK_EXCLUDE=infra yarn lefthook run check-all
