name: Push to branch
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    name: Build cy7.io
    runs-on: ubuntu-20.04
    env:
      GATSBY_BUILD_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.18.0
      - uses: ./.github/actions/yarn-install
      - run: yarn build
      - name: Store generated code
        uses: actions/upload-artifact@v2
        with:
          name: generated
          path: generated
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.18.0
      - uses: ./.github/actions/yarn-install
      - run: yarn build-storybook --docs --quiet
  check-frontend-code-quality:
    name: Check frontend code quality
    needs: build
    uses: ./.github/workflows/check-frontend-code-quality.yml
  check-terraform-code-quality:
    name: Check Terraform code quality
    uses: ./.github/workflows/check-terraform-code-quality.yml
    secrets: inherit
