name: validate-pushed-code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook --docs --quiet
  check-frontend-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: LEFTHOOK_EXCLUDE=infra yarn lefthook run check-all
