name: validate-pushed-code
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GATSBY_BUILD_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - name: Store generated code
        uses: actions/upload-artifact@v2
        with:
          name: generated
          path: generated
  build-storybook:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
      - uses: bahmutov/npm-install@v1
      - run: yarn build-storybook --docs --quiet
  check-frontend-code-quality:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
      - name: Download generated code
        uses: actions/download-artifact@v2
        with:
          name: generated
          path: generated
      - uses: bahmutov/npm-install@v1
      - run: LEFTHOOK_EXCLUDE=infra yarn lefthook run check-all
  check-terraform-code-quality:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: deploy/infra
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
